spring:
  profiles:
    active: cbrf

api:
  cbrf:
    url: http://www.cbr.ru/scripts/XML_daily.asp
    onDate: ?date_req=
  nbrb:
    url: https://api.nbrb.by/exrates/rates/
    mode: ?parammode=2
    onDate: ondate=